sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
      - pip_download_cache

env:
  - TRAVIS="True"

install:
 - pip install git+https://github.com/aneumeier/questions#master
 - pip install coveralls
 - pip install pytest-django
 - python setup.py install
script:
    - py.test tests --ds=tests.settings
after_success:
  - coveralls
